package com.bombay.restaurantintelligence.openclaw;

public enum DashboardIntent {
    TODAY_SALES,
    YESTERDAY_SALES,
    DATE_RANGE_SALES,
    TODAY_EXPENSES,
    YESTERDAY_EXPENSES,
    DATE_RANGE_EXPENSES,
    TODAY_PROFIT,
    THIS_WEEK_SALES,
    THIS_MONTH_SALES,
    THIS_WEEK_EXPENSES,
    THIS_MONTH_EXPENSES,
    VENDOR_SPEND,
    CATEGORY_SPEND,
    SALARY_TOTAL,
    EMPLOYEE_SALARY,
    CASH_SALES,
    UPI_SALES,
    ZOMATO_SALES,
    SWIGGY_SALES,
    SALES_COMPARISON,
    EXPENSE_COMPARISON,
    PENDING_REVIEW_COUNT
}
