package com.bombay.restaurantintelligence.whatsapp;
import com.fasterxml.jackson.databind.JsonNode; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.reactive.function.client.WebClient; import java.net.URI; import java.util.Map;
@Service @ConditionalOnProperty(name="app.whatsapp.mode",havingValue="meta")
public class MetaWhatsAppService implements WhatsAppService {
 private final WebClient client; private final String token; private final String phoneNumberId; private final String graphBase;
 public MetaWhatsAppService(WebClient.Builder builder,@Value("${app.whatsapp.access-token}") String token,@Value("${app.whatsapp.phone-number-id}") String phoneNumberId,@Value("${WHATSAPP_GRAPH_BASE_URL:https://graph.facebook.com/v23.0}") String graphBase){this.client=builder.build();this.token=token;this.phoneNumberId=phoneNumberId;this.graphBase=graphBase;}
 @Override public void sendText(String recipient,String text){client.post().uri(graphBase+"/"+phoneNumberId+"/messages").headers(h->h.setBearerAuth(token)).contentType(MediaType.APPLICATION_JSON).bodyValue(Map.of("messaging_product","whatsapp","to",recipient,"type","text","text",Map.of("body",text))).retrieve().toBodilessEntity().block();}
 @Override public MediaPayload downloadMedia(String mediaId,String fallbackFilename){JsonNode meta=client.get().uri(graphBase+"/"+mediaId).headers(h->h.setBearerAuth(token)).retrieve().bodyToMono(JsonNode.class).block();if(meta==null||meta.path("url").isMissingNode())throw new IllegalStateException("Meta media URL missing");String url=meta.path("url").asText();String mime=meta.path("mime_type").asText("application/octet-stream");byte[] data=client.get().uri(URI.create(url)).headers(h->h.setBearerAuth(token)).retrieve().bodyToMono(byte[].class).block();return new MediaPayload(data==null?new byte[0]:data,mime,fallbackFilename==null?mediaId:fallbackFilename);}
}
