package com.bombay.restaurantintelligence.analytics;

import com.bombay.restaurantintelligence.domain.*; import com.bombay.restaurantintelligence.repository.TransactionRepository; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.*; import java.time.*; import java.util.*; import java.util.function.Predicate; import java.util.stream.Collectors;

@Service public class AnalyticsService {
 private static final ZoneId BUSINESS_ZONE=ZoneId.of("Asia/Kolkata"); private final TransactionRepository transactions;
 public AnalyticsService(TransactionRepository transactions){this.transactions=transactions;}
 @Transactional(readOnly=true) public DashboardData dashboard(LocalDate from,LocalDate to){LocalDate today=LocalDate.now(BUSINESS_ZONE);if(from==null)from=today;if(to==null)to=today;if(to.isBefore(from))throw new IllegalArgumentException("to must be on or after from");LocalDate monthStart=today.withDayOfMonth(1);
   Summary todaySummary=summarize(load(today,today));Summary mtd=summarize(load(monthStart,today));List<TransactionEntity> selected=load(from,to);Summary selectedSummary=summarize(selected);List<DailyPoint> daily=daily(selected,from,to);List<NamedAmount> category=group(selected,t->isExpense(t)&&t.getCategory()!=null,t->t.getCategory().getCode());List<NamedAmount> vendor=group(selected,t->isExpense(t)&&t.getVendor()!=null,t->t.getVendor().getName());Map<String,BigDecimal> channel=channelSplit(selected);Map<String,BigDecimal> aggregators=aggregatorSplit(selected);Comparison comparison=comparison(from,to,selectedSummary.sales());String first=transactions.findFirstByStatusOrderByBusinessDateAsc(TransactionStatus.VERIFIED).map(t->t.getBusinessDate().toString()).orElse(null);return new DashboardData(today,from,to,first,todaySummary,mtd,selectedSummary,daily,category,vendor,channel,aggregators,comparison);
 }
 private List<TransactionEntity> load(LocalDate from,LocalDate to){return transactions.findByStatusAndBusinessDateBetweenOrderByBusinessDateAscCreatedAtAsc(TransactionStatus.VERIFIED,from,to);}
 public Summary summarize(List<TransactionEntity> txs){BigDecimal sales=sum(txs,this::isSale);BigDecimal expenses=sum(txs,this::isExpense);BigDecimal vendor=sum(txs,t->t.getTransactionType()==TransactionType.VENDOR_PAYMENT);BigDecimal online=sum(txs,t->isCategory(t,"ONLINE_SALES","ZOMATO_SALES","SWIGGY_SALES"));BigDecimal offline=sum(txs,t->isCategory(t,"IN_STORE_SALES","CASH_SALES","UPI_SALES"));BigDecimal advertising=sum(txs,t->t.getTransactionType()==TransactionType.ADVERTISING);BigDecimal salary=sum(txs,t->t.getTransactionType()==TransactionType.SALARY);int orderCount=(int)txs.stream().filter(t->isCategory(t,"ZOMATO_SALES","SWIGGY_SALES","ONLINE_SALES")).count();BigDecimal aov=orderCount==0?BigDecimal.ZERO:online.divide(BigDecimal.valueOf(orderCount),2,RoundingMode.HALF_UP);return new Summary(sales,expenses,sales.subtract(expenses),vendor,online,offline,advertising,salary,aov,orderCount);}
 private Comparison comparison(LocalDate from,LocalDate to,BigDecimal current){long days=Duration.between(from.atStartOfDay(),to.plusDays(1).atStartOfDay()).toDays();LocalDate prevTo=from.minusDays(1),prevFrom=prevTo.minusDays(days-1);List<TransactionEntity> prev=load(prevFrom,prevTo);if(prev.isEmpty())return new Comparison(null,null,null,"Not enough data for comparison");BigDecimal previous=summarize(prev).sales();if(previous.signum()==0)return new Comparison(current,previous,null,"Not enough data for percentage comparison");BigDecimal pct=current.subtract(previous).multiply(BigDecimal.valueOf(100)).divide(previous,2,RoundingMode.HALF_UP);return new Comparison(current,previous,pct,null);}
 private List<DailyPoint> daily(List<TransactionEntity> txs,LocalDate from,LocalDate to){Map<LocalDate,List<TransactionEntity>> by=txs.stream().collect(Collectors.groupingBy(TransactionEntity::getBusinessDate));List<DailyPoint> out=new ArrayList<>();for(LocalDate d=from;!d.isAfter(to);d=d.plusDays(1)){List<TransactionEntity> day=by.getOrDefault(d,List.of());out.add(new DailyPoint(d,sum(day,this::isSale),sum(day,this::isExpense)));}return out;}
 private List<NamedAmount> group(List<TransactionEntity> txs,Predicate<TransactionEntity> include,java.util.function.Function<TransactionEntity,String> key){Map<String,BigDecimal> m=new HashMap<>();for(var t:txs)if(include.test(t))m.merge(key.apply(t),t.getAmount(),BigDecimal::add);return m.entrySet().stream().sorted(Map.Entry.<String,BigDecimal>comparingByValue().reversed()).map(e->new NamedAmount(e.getKey(),e.getValue())).toList();}
 private Map<String,BigDecimal> channelSplit(List<TransactionEntity> txs){Map<String,BigDecimal> m=new LinkedHashMap<>();m.put("ONLINE",sum(txs,t->isCategory(t,"ONLINE_SALES","ZOMATO_SALES","SWIGGY_SALES")));m.put("OFFLINE",sum(txs,t->isCategory(t,"IN_STORE_SALES","CASH_SALES","UPI_SALES")));return m;}
 private Map<String,BigDecimal> aggregatorSplit(List<TransactionEntity> txs){Map<String,BigDecimal> m=new LinkedHashMap<>();m.put("ZOMATO",sum(txs,t->isCategory(t,"ZOMATO_SALES")));m.put("SWIGGY",sum(txs,t->isCategory(t,"SWIGGY_SALES")));return m;}
 private BigDecimal sum(List<TransactionEntity> txs,Predicate<TransactionEntity> p){return txs.stream().filter(p).map(TransactionEntity::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);}
 private boolean isSale(TransactionEntity t){return t.getTransactionType()==TransactionType.SALE;} private boolean isExpense(TransactionEntity t){return switch(t.getTransactionType()){case SALE,SETTLEMENT,REFUND->false;default->true;};}
 private static boolean isCategory(TransactionEntity t,String... codes){if(t.getCategory()==null)return false;for(String c:codes)if(c.equals(t.getCategory().getCode()))return true;return false;}
 public record Summary(BigDecimal sales,BigDecimal expenses,BigDecimal netOperatingResult,BigDecimal vendorPayments,BigDecimal onlineSales,BigDecimal offlineSales,BigDecimal advertising,BigDecimal salary,BigDecimal averageOrderValue,int onlineOrderCount){}
 public record DailyPoint(LocalDate date,BigDecimal sales,BigDecimal expenses){} public record NamedAmount(String name,BigDecimal amount){} public record Comparison(BigDecimal currentSales,BigDecimal previousSales,BigDecimal changePercent,String message){}
 public record DashboardData(LocalDate today,LocalDate from,LocalDate to,String dataAvailableFrom,Summary todaySummary,Summary monthToDate,Summary selected,List<DailyPoint> daily,List<NamedAmount> categoryExpenses,List<NamedAmount> vendorSpending,Map<String,BigDecimal> onlineVsOffline,Map<String,BigDecimal> zomatoVsSwiggy,Comparison comparison){}
}
