package com.bombay.restaurantintelligence.domain;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.UUID;
@Entity @Table(name="transactions") public class TransactionEntity {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id;
 @Column(name="business_date",nullable=false) private LocalDate businessDate;
 @Enumerated(EnumType.STRING) @Column(name="transaction_type",nullable=false) private TransactionType transactionType;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="category_id") private Category category;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="vendor_id") private Vendor vendor;
 @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="employee_id") private Employee employee;
 @Column(nullable=false,precision=19,scale=2) private BigDecimal amount; @Column(nullable=false,length=3) private String currency="INR"; @Column(columnDefinition="TEXT") private String description;
 @Column(name="source_type",nullable=false) private String sourceType; @Column(name="source_reference") private String sourceReference; @Column(name="source_message_id") private String sourceMessageId; @Column(name="source_filename") private String sourceFilename; private String sender; @Column(name="received_at") private Instant receivedAt; @Column(name="raw_text",columnDefinition="TEXT") private String rawText; @Column(name="original_file_location") private String originalFileLocation; @Column(name="file_checksum") private String fileChecksum;
 @Column(name="extraction_confidence",precision=5,scale=4) private BigDecimal extractionConfidence; @Column(name="normalization_confidence",precision=5,scale=4) private BigDecimal normalizationConfidence; @Column(name="normalized_fingerprint",length=64) private String normalizedFingerprint;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private TransactionStatus status; @Column(name="created_at",nullable=false) private Instant createdAt=Instant.now(); @Column(name="updated_at",nullable=false) private Instant updatedAt=Instant.now();
 public TransactionEntity(){}
 public UUID getId(){return id;} public LocalDate getBusinessDate(){return businessDate;} public TransactionType getTransactionType(){return transactionType;} public Category getCategory(){return category;} public Vendor getVendor(){return vendor;} public Employee getEmployee(){return employee;} public BigDecimal getAmount(){return amount;} public String getCurrency(){return currency;} public String getDescription(){return description;} public String getSourceType(){return sourceType;} public String getSourceReference(){return sourceReference;} public String getSourceMessageId(){return sourceMessageId;} public String getSourceFilename(){return sourceFilename;} public String getSender(){return sender;} public Instant getReceivedAt(){return receivedAt;} public String getRawText(){return rawText;} public String getOriginalFileLocation(){return originalFileLocation;} public String getFileChecksum(){return fileChecksum;} public BigDecimal getExtractionConfidence(){return extractionConfidence;} public BigDecimal getNormalizationConfidence(){return normalizationConfidence;} public TransactionStatus getStatus(){return status;} public Instant getCreatedAt(){return createdAt;}
 public void setBusinessDate(LocalDate v){businessDate=v;} public void setTransactionType(TransactionType v){transactionType=v;} public void setCategory(Category v){category=v;} public void setVendor(Vendor v){vendor=v;} public void setEmployee(Employee v){employee=v;} public void setAmount(BigDecimal v){amount=v;} public void setDescription(String v){description=v;} public void setSourceType(String v){sourceType=v;} public void setSourceReference(String v){sourceReference=v;} public void setSourceMessageId(String v){sourceMessageId=v;} public void setSourceFilename(String v){sourceFilename=v;} public void setSender(String v){sender=v;} public void setReceivedAt(Instant v){receivedAt=v;} public void setRawText(String v){rawText=v;} public void setOriginalFileLocation(String v){originalFileLocation=v;} public void setFileChecksum(String v){fileChecksum=v;} public void setExtractionConfidence(BigDecimal v){extractionConfidence=v;} public void setNormalizationConfidence(BigDecimal v){normalizationConfidence=v;} public void setNormalizedFingerprint(String v){normalizedFingerprint=v;} public void setStatus(TransactionStatus v){status=v;updatedAt=Instant.now();}
}
