import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Summary={sales:number;expenses:number;netOperatingResult:number;vendorPayments:number;onlineSales:number;offlineSales:number;advertising:number;salary:number;averageOrderValue:number;onlineOrderCount:number};
type Dashboard={today:string;from:string;to:string;dataAvailableFrom:string|null;todaySummary:Summary;monthToDate:Summary;selected:Summary;daily:{date:string;sales:number;expenses:number}[];categoryExpenses:{name:string;amount:number}[];vendorSpending:{name:string;amount:number}[];onlineVsOffline:Record<string,number>;zomatoVsSwiggy:Record<string,number>;comparison:{currentSales:number|null;previousSales:number|null;changePercent:number|null;message:string|null}};
type Transaction={id:string;businessDate:string;type:string;category:string|null;vendor:string|null;employee:string|null;amount:number;currency:string;status:string;sourceType:string;createdAt:string};
type Review={id:string;transactionId:string;reason:string;status:string;businessDate:string;amount:number;rawText:string|null;category:string|null;vendor:string|null};
type Category={code:string;name:string;group:string};
type ImportItem={id:string;sourceType:string;sourceReference:string;status:string;recordCount:number;createdAt:string};
type TxDetail=Record<string,unknown>&{auditHistory:unknown[]};
type ApiFn=<T>(p:string,o?:RequestInit)=>Promise<T>;
const money=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const iso=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const rangeFor=(key:string)=>{const now=new Date();const today=iso(now);if(key==='today')return [today,today];if(key==='yesterday'){const d=new Date(now);d.setDate(d.getDate()-1);return [iso(d),iso(d)];}if(key==='week'){const d=new Date(now);const offset=(d.getDay()+6)%7;d.setDate(d.getDate()-offset);return [iso(d),today];}if(key==='month'){const d=new Date(now.getFullYear(),now.getMonth(),1);return [iso(d),today];}if(key==='prevmonth'){const a=new Date(now.getFullYear(),now.getMonth()-1,1),b=new Date(now.getFullYear(),now.getMonth(),0);return [iso(a),iso(b)];}return [today,today];};

export function App(){
 const [auth,setAuth]=useState(sessionStorage.getItem('bri-auth')||''); const [loginError,setLoginError]=useState('');
 const [filter,setFilter]=useState('today'); const [[from,to],setRange]=useState(rangeFor('today')); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [transactions,setTransactions]=useState<Transaction[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [imports,setImports]=useState<ImportItem[]>([]); const [notice,setNotice]=useState(''); const [detail,setDetail]=useState<TxDetail|null>(null); const [loading,setLoading]=useState(false);
 const api=useCallback(async<T,>(path:string,options:RequestInit={}):Promise<T>=>{const headers=new Headers(options.headers);if(auth)headers.set('Authorization',auth);if(options.body&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');const r=await fetch(path,{...options,headers});if(r.status===401){setAuth('');sessionStorage.removeItem('bri-auth');throw new Error('Authentication required');}const text=await r.text();if(!r.ok){let msg=text;try{msg=JSON.parse(text).message||text}catch{}throw new Error(msg||`Request failed: ${r.status}`)}return (text?JSON.parse(text):undefined) as T;},[auth]);
 const refresh=useCallback(async()=>{if(!auth)return;setLoading(true);try{const [d,t,r,c,i]=await Promise.all([api<Dashboard>(`/api/analytics/dashboard?from=${from}&to=${to}`),api<Transaction[]>('/api/transactions'),api<Review[]>('/api/reviews'),api<Category[]>('/api/categories'),api<ImportItem[]>('/api/imports')]);setDashboard(d);setTransactions(t);setReviews(r);setCategories(c);setImports(i);}catch(e){setNotice((e as Error).message)}finally{setLoading(false)}},[api,auth,from,to]);
 useEffect(()=>{void refresh()},[refresh]);
 const selectFilter=(v:string)=>{setFilter(v);if(v!=='custom')setRange(rangeFor(v));};
 const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const token='Basic '+btoa(`${fd.get('username')}:${fd.get('password')}`);try{const r=await fetch('/api/auth/check',{headers:{Authorization:token}});if(!r.ok)throw new Error();sessionStorage.setItem('bri-auth',token);setAuth(token);setLoginError('');}catch{setLoginError('Invalid owner credentials')}};
 if(!auth)return <Login onSubmit={login} error={loginError}/>;
 const channel=Object.entries(dashboard?.onlineVsOffline ?? {}).map(([name,value])=>({name,value:Number(value)})); const aggregators=Object.entries(dashboard?.zomatoVsSwiggy ?? {}).map(([name,value])=>({name,value:Number(value)}));
 return <div className="app-shell"><header><div><p className="eyebrow">PRIVATE OWNER CONSOLE</p><h1>Bombay Restaurant Intelligence</h1><p className="subtle">{dashboard?.dataAvailableFrom?`Data available from ${dashboard.dataAvailableFrom}`:'No verified transactions yet'}</p></div><div className="header-actions"><span className={loading?'status busy':'status'}>{loading?'Refreshing…':'Live'}</span><button className="ghost" onClick={()=>{sessionStorage.removeItem('bri-auth');setAuth('')}}>Sign out</button></div></header>
 <main>
  {notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}</div>}
  <section className="toolbar"><div className="filters">{[['today','Today'],['yesterday','Yesterday'],['week','This Week'],['month','This Month'],['prevmonth','Previous Month'],['custom','Custom']].map(([k,l])=><button key={k} className={filter===k?'active':''} onClick={()=>selectFilter(k)}>{l}</button>)}</div>{filter==='custom'&&<div className="date-range"><input type="date" value={from} onChange={e=>setRange([e.target.value,to])}/><span>to</span><input type="date" value={to} onChange={e=>setRange([from,e.target.value])}/></div>}</section>
  <section><div className="section-title"><div><p className="eyebrow">TODAY</p><h2>Operating pulse</h2></div></div><CardGrid summary={dashboard?.todaySummary}/></section>
  <section><div className="section-title"><div><p className="eyebrow">MONTH TO DATE</p><h2>Financial position</h2></div></div><div className="cards six"><Metric label="Sales" value={dashboard?.monthToDate.sales}/><Metric label="Expenses" value={dashboard?.monthToDate.expenses}/><Metric label="Net operating result" value={dashboard?.monthToDate.netOperatingResult}/><Metric label="Advertising" value={dashboard?.monthToDate.advertising}/><Metric label="Salary" value={dashboard?.monthToDate.salary}/><Metric label="Vendor purchases" value={dashboard?.monthToDate.vendorPayments}/></div></section>
  <section className="input-panel"><div><p className="eyebrow">QUICK INTAKE</p><h2>Record business activity</h2><p className="subtle">Uses the same Intake → Normalization → PostgreSQL pipeline as WhatsApp and files.</p></div><ManualEntry api={api} onDone={async m=>{setNotice(m);await refresh()}}/><FileUpload api={api} onDone={async m=>{setNotice(m);await refresh()}}/></section>
  <section className="chart-grid"><ChartCard title="Daily sales & expense trend"><ResponsiveContainer width="100%" height={280}><AreaChart data={dashboard?.daily||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tickFormatter={v=>`₹${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money.format(Number(v))}/><Legend/><Area type="monotone" dataKey="sales" fillOpacity={.18}/><Area type="monotone" dataKey="expenses" fillOpacity={.08}/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Expense categories"><ResponsiveContainer width="100%" height={280}><BarChart data={dashboard?.categoryExpenses||[]} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" tickFormatter={v=>`₹${Math.round(v/1000)}k`}/><YAxis type="category" dataKey="name" width={120} tick={{fontSize:10}}/><Tooltip formatter={v=>money.format(Number(v))}/><Bar dataKey="amount"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Vendor spending"><ResponsiveContainer width="100%" height={280}><BarChart data={(dashboard?.vendorSpending||[]).slice(0,8)}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tickFormatter={v=>`₹${Math.round(v/1000)}k`}/><Tooltip formatter={v=>money.format(Number(v))}/><Bar dataKey="amount"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Channel mix"><div className="pie-row"><MiniPie title="Online vs offline" data={channel}/><MiniPie title="Zomato vs Swiggy" data={aggregators}/></div></ChartCard></section>
  <section className="comparison"><p className="eyebrow">COMPARISON</p><h3>{dashboard?.comparison.message||`${dashboard?.comparison.changePercent}% sales vs previous comparable period`}</h3></section>
  <section className="two-col"><Panel title={`Review required (${reviews.length})`}><ReviewTable reviews={reviews} categories={categories} api={api} onDone={refresh}/></Panel><Panel title="Recent imports"><ImportsTable items={imports}/></Panel></section>
  <section><Panel title="Recent transactions"><TransactionsTable items={transactions} onOpen={async id=>{try{setDetail(await api<TxDetail>(`/api/transactions/${id}`))}catch(e){setNotice((e as Error).message)}}}/></Panel></section>
 </main>{detail&&<DetailModal detail={detail} onClose={()=>setDetail(null)}/>}</div>
}
function Login({onSubmit,error}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;error:string}){return <div className="login-page"><form className="login-card" onSubmit={onSubmit}><p className="eyebrow">PRIVATE APPLICATION</p><h1>Bombay Restaurant Intelligence</h1><p>Owner sign in</p><label>Username<input name="username" autoComplete="username" required autoFocus/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<div className="error">{error}</div>}<button type="submit" className="primary">Sign in</button></form></div>}
function CardGrid({summary}:{summary?:Summary}){return <div className="cards"><Metric label="Total Sales" value={summary?.sales}/><Metric label="Total Expenses" value={summary?.expenses}/><Metric label="Vendor Payments" value={summary?.vendorPayments}/><Metric label="Online Sales" value={summary?.onlineSales}/><Metric label="Offline Sales" value={summary?.offlineSales}/></div>}
function Metric({label,value}:{label:string;value?:number}){return <article className="metric"><span>{label}</span><strong>{money.format(value||0)}</strong></article>}
function ManualEntry({api,onDone}:{api:ApiFn;onDone:(m:string)=>void}){const [text,setText]=useState('Paid Salman 6500 for vegetables');const [busy,setBusy]=useState(false);return <form className="manual" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await api<{message:string;status:string}>('/api/intake/manual-text',{method:'POST',body:JSON.stringify({text})});onDone(`${r.status}: ${r.message}`);setText('')}catch(e){onDone((e as Error).message)}finally{setBusy(false)}}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Paid Salman 6500 vegetables" required/><button className="primary" disabled={busy}>{busy?'Recording…':'Record'}</button></form>}
function FileUpload({api,onDone}:{api:ApiFn;onDone:(m:string)=>void}) {
 const [file,setFile]=useState<File|null>(null);
 const [preview,setPreview]=useState<{jobId:string;recordCount:number;filename:string}|null>(null);
 const previewFile=async()=>{
  if(!file)return;
  const fd=new FormData(); fd.append('file',file);
  try {
   const result=await api<{jobId:string;recordCount:number;filename:string}>('/api/intake/uploads/preview',{method:'POST',body:fd});
   setPreview(result);
  } catch(e){onDone((e as Error).message);}
 };
 const confirmImport=async()=>{
  if(!preview)return;
  try {
   const result=await api<{processed:number}>(`/api/intake/uploads/${preview.jobId}/confirm`,{method:'POST'});
   onDone(`Imported ${result.processed} records`); setPreview(null); setFile(null);
  } catch(e){onDone((e as Error).message);}
 };
 return <div className="upload">
  <input type="file" accept=".xls,.xlsx,.csv,image/*" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/>
  <button className="ghost" disabled={!file} onClick={previewFile}>Preview</button>
  {preview&&<>
   <span>{preview.recordCount} candidate records</span>
   <button className="primary" onClick={confirmImport}>Confirm import</button>
  </>}
 </div>;
}

function ChartCard({title,children}:{title:string;children:React.ReactNode}){return <article className="chart-card"><h3>{title}</h3>{children}</article>}
function MiniPie({title,data}:{title:string;data:{name:string;value:number}[]}){return <div className="mini-pie"><h4>{title}</h4><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={data} dataKey="value" nameKey="name" outerRadius={72} label/><Tooltip formatter={v=>money.format(Number(v))}/></PieChart></ResponsiveContainer></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <article className="panel"><div className="panel-head"><h3>{title}</h3></div>{children}</article>}
function TransactionsTable({items,onOpen}:{items:Transaction[];onOpen:(id:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Vendor</th><th>Amount</th><th>Status</th><th>Source</th></tr></thead><tbody>{items.map(t=><tr key={t.id} onClick={()=>onOpen(t.id)} className="clickable"><td>{t.businessDate}</td><td>{pretty(t.type)}</td><td>{pretty(t.category)}</td><td>{t.vendor||'—'}</td><td>{money.format(t.amount)}</td><td><span className={`pill ${t.status.toLowerCase()}`}>{pretty(t.status)}</span></td><td>{pretty(t.sourceType)}</td></tr>)}{!items.length&&<tr><td colSpan={7} className="empty">No transactions yet</td></tr>}</tbody></table></div>}
function ReviewTable({reviews,categories,api,onDone}:{reviews:Review[];categories:Category[];api:ApiFn;onDone:()=>Promise<void>}){return <div className="review-list">{reviews.map(r=><ReviewRow key={r.id} review={r} categories={categories} api={api} onDone={onDone}/>)}{!reviews.length&&<div className="empty">Nothing needs review.</div>}</div>}
function ReviewRow({review:r,categories,api,onDone}:{review:Review;categories:Category[];api:ApiFn;onDone:()=>Promise<void>}){const [categoryCode,setCategory]=useState(r.category||'');const [amount,setAmount]=useState(String(r.amount||''));const [vendor,setVendor]=useState(r.vendor||'');return <div className="review-row"><div><strong>{r.rawText||'Imported candidate'}</strong><p>{r.reason}</p></div><div className="review-fields"><select value={categoryCode} onChange={e=>setCategory(e.target.value)}><option value="">Choose category</option>{categories.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select><input value={vendor} onChange={e=>setVendor(e.target.value)} placeholder="Vendor"/><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="primary small" onClick={async()=>{await api(`/api/reviews/${r.id}/approve`,{method:'POST',body:JSON.stringify({categoryCode,vendor,amount:Number(amount),rawTerm:r.rawText,reason:'Owner approved in dashboard'})});await onDone()}}>Approve</button><button className="ghost small" onClick={async()=>{await api(`/api/reviews/${r.id}/reject`,{method:'POST',body:JSON.stringify({reason:'Owner rejected in dashboard'})});await onDone()}}>Reject</button></div></div>}
function ImportsTable({items}:{items:ImportItem[]}){return <div className="table-wrap"><table><thead><tr><th>Source</th><th>File</th><th>Records</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{pretty(i.sourceType)}</td><td>{i.sourceReference||'—'}</td><td>{i.recordCount}</td><td>{pretty(i.status)}</td></tr>)}{!items.length&&<tr><td colSpan={4} className="empty">No imports yet</td></tr>}</tbody></table></div>}
function DetailModal({detail,onClose}:{detail:TxDetail;onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><div className="panel-head"><h3>Transaction source & audit</h3><button className="ghost" onClick={onClose}>Close</button></div><dl>{Object.entries(detail).filter(([k])=>k!=='auditHistory').map(([k,v])=><div key={k}><dt>{pretty(k)}</dt><dd>{v==null?'—':typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl><h4>Audit history</h4><pre>{JSON.stringify(detail.auditHistory,null,2)}</pre></div></div>}
function pretty(v:string|null|undefined){return v? v.replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):'—'}
